### ISSUE TITLE
Failed to install dvm on Windows & through PowerShell 4.0

### ISSUE THREAD

**Issue by jianwu-github** [howtowhale/dvm#162]
PS C:\Users\Jian> iwr 'https://howtowhale.github.io/dvm/downloads/latest/install.ps1' -UseBasicParsi
ng | iex
Downloading dvm.ps1...
Downloading dvm.cmd...
Downloading dvm-helper.exe...
iex : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error:
(404) Not Found."
At line:1 char:88
+ ... BasicParsing | iex
+                    ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by carolynvs** [comment]
Thanks for reporting this. I've fixed the windows install script ([v0.8.3](https://github.com/howtowhale/dvm/releases/tag/0.8.3)) so if you run it again, it should work.
