### ISSUE TITLE
Installing error on Ubuntu 16.04

### ISSUE THREAD

**Issue by dev-lusaja** [howtowhale/dvm#164]
I have installed dvm with the install.sh

====================
Downloading dvm.sh...
######################################################################## 100,0%
Downloading bash_completion
######################################################################## 100,0%
Downloading dvm-helper...
######################################################################## 100,0%

Docker Version Manager (dvm) has been installed to ~/.dvm
Run the following command to start using dvm. Then add it to your bash profile (e.g. ~/.bashrc or ~/.bash_profile) to complete the installation.

  source ~/.dvm/dvm.sh
====================

when I execute the source command "source ~/.dvm/dvm.sh", this command print in the screen:

====================
~/.dvm/dvm.sh:30: command not found: cd
====================

**Comment by carolynvs** [comment]
Is this with bash or are you running another shell, like zsh?

**Comment by dev-lusaja** [comment]
Hi, im using zsh, I read the other issues and I look a solution,  modify the line 30 in the script.
"command cd . . . ."  to "cd . . ."

**Comment by carolynvs** [comment]
I think this has been fixed by #176.
