### ISSUE TITLE
Installing version in new naming scheme fails with http status 403

### ISSUE THREAD

**Issue by knoxilla** [howtowhale/dvm#166]
If you are reporting a bug, please use the template below:

### What didn't work?
Run the command(s) that failed (or did not behave properly) again with the `--debug` flag and include the output.

```
$ dvm --debug  install 17.03.2-ce
The dvm home directory is: /Users/tknox/.dvm
dvm install 17.03.2-ce
Retrieving Docker releases
Ignoring non-semver Docker release: v.1.13.0-rc5
Installing 17.03.2-ce...
Downloading https://get.docker.com/builds/Darwin/x86_64/docker-17.03.2-ce.tgz
Unable to download https://get.docker.com/builds/Darwin/x86_64/docker-17.03.2-ce.tgz. (Status 403)
```

### What should it have done?
Let us know what you expected the command above to do.

Expected it to install the 17.03.2-ce version into my ~/.dvm/bin directory.

### Helpful Context
If you can provide the following info, it will help us figure things out more quickly! :smile:

What version of dvm are you using?

```
dvm --version
Docker Version Manager version 0.8.3 ()
```

What is your Operating System?

OSX Sierra

What is your shell (bash/powershell/cmd/fish)?

Bash

How did you install dvm (command-line,chocolatey,homebrew)?

Homebrew

Do you like kittens? :smile_cat:

Indeed!

I think Docker must have moved where they are placing build archives. with the new versioning scheme.  

Thanks!

**Comment by carolynvs** [comment]
Thanks for the heads up!

**Comment by carolynvs** [comment]
https://github.com/moby/moby/issues/33951

**Comment by kingdonb** [comment]
Is the status of that report, that they are just not providing old docker releases anymore?

What is a kubeadm user to do, who needs v1.12.6 and not later version, on some release of Debian other than Ubuntu LTS?

**Comment by carolynvs** [comment]
More changes were made as well:

* experimental builds published to a new location which embeds the version name. So we can't use a static URL anymore to get the latest unknown version (e.g. https://experimental.docker.com/builds/Darwin/x86_64/docker-latest.tgz is no longer updated). We need to grab from https://download.docker.com/linux/static/edge/x86_64/.
* release candidates have a different location `/test/` instead of `test.docker.com`. https://download.docker.com/mac/static/test/x86_64/docker-17.03.1-ce-rc1.tgz
* The OS name embedded in the URL has changed. Darwin => mac, Windows => win, Linux => linux.

**Comment by carolynvs** [comment]
I've updated dvm to work with the new location, only to find out that they aren't consistently publishing binaries for all operating systems. https://github.com/docker/for-linux/issues/83

I'm going to hold off on a new release until I hear back on how this is all supposed to work...

**Comment by carolynvs** [comment]
Okay, that specific version is has reached its "End of Life" and is not supported, so it's no longer available. I'll cut a release shortly with what's working now, it will let you grab supported versions, though be warned there are open issues for edge and prereleases.

**Comment by carolynvs** [comment]
[dvm 0.9.0](https://github.com/howtowhale/dvm/releases/tag/0.9.0) has been released. Working on a homebrew now...
