### ISSUE TITLE
Missing version 17.06.0

### ISSUE THREAD

**Issue by richardsondx** [howtowhale/dvm#174]
macbook-pro:~ rdackam$ dvm ls-remote
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.11.1
1.11.2
1.12.0
1.12.1
1.12.2
1.12.3
1.12.4
1.12.5
1.12.6
1.13.0
1.13.1
17.03.0-ce
17.03.1-ce
17.03.2-ce
17.04.0-ce
17.05.0-ce

**Comment by carolynvs** [comment]
Docker is no longer consistently tagging releases on github which is what drives the listing mechanism... 🔥 

Thanks for reporting! I'm on dvm damage control rewriting ... pretty much all of dvm to deal everything being broken. Hopefully I'll have another release in next couple days to fix.

**Comment by carolynvs** [comment]
Okay so that took longer than I had hoped but I've released a new version of dvm (v1.0.0) that fixes everything that Docker broke. If you are still using dvm, give it a try!
