### ISSUE TITLE
dvm detect fails because sha256 is not found

### ISSUE THREAD

**Issue by jonathanpdx** [howtowhale/dvm#184]
If you are reporting a bug, please use the template below:

### What didn't work?
Run the command(s) that failed (or did not behave properly) again with the `--debug` flag and include the output.

```
$ dvm --debug detect
The dvm home directory is: /Users/jonathangordon/.dvm
dvm detect
dvm detect
Queried /version and got Version: 17.09.0-ce
Detected client version: 17.09.0-ce
Writing to /Users/jonathangordon/.dvm/.tmp/dvm-output.sh...
export DOCKER_VERSION="17.09.0-ce"
Checking if version is installed: 17.09.0-ce
/usr/local/bin/docker -v output: Docker version 17.09.0-ce, build afdb6d4

17.09.0-ce is not installed. Installing now...
Skipping version validation!
Installing 17.09.0-ce...
Downloading https://download.docker.com/mac/static/stable/x86_64/docker-17.09.0-ce.tgz
Downloading https://download.docker.com/mac/static/stable/x86_64/docker-17.09.0-ce.tgz.sha256
Unable to download https://download.docker.com/mac/static/stable/x86_64/docker-17.09.0-ce.tgz.sha256. (Status 404)
```

### What should it have done?
I can confirm that the .tgz is there but the .tgs.sha256 isn't. Perhaps they're in a new location?

### Helpful Context
If you can provide the following info, it will help us figure things out more quickly! :smile:

What version of dvm are you using?

```
$ dvm --version
Docker Version Manager version 0.9.1 ()
```

What is your Operating System?

Mac OS Sierra, Version 10.12.6 (16G29

What is your shell (bash/powershell/cmd/fish)?

bash

How did you install dvm (command-line,chocolatey,homebrew)?

homebrew

Do you like kittens? :smile_cat:

Yas!

**Comment by carolynvs** [comment]
I believe this is fixed on the latest version so I am closing this issue. If you are still having trouble, just leave a comment and I'll reopen.
