### ISSUE TITLE
Unable to download docker-17.09.0-ce

### ISSUE THREAD

**Issue by rayjohnson** [howtowhale/dvm#185]
If you are reporting a bug, please use the template below:

### What didn't work?
dvm detect failed

```
$ dvm detect
17.09.0-ce is not installed. Installing now...
Installing 17.09.0-ce...
Unable to download https://download.docker.com/mac/static/stable/x86_64/docker-17.09.0-ce.tgz.sha256. (Status 404)

```

### What should it have done?

Should have downloaded

### Helpful Context
If you can provide the following info, it will help us figure things out more quickly! :smile:

What version of dvm are you using?

```
$ dvm --version
Docker Version Manager version 0.9.0 ()
```

What is your Operating System?
Mac

What is your shell (bash/powershell/cmd/fish)?
bash

How did you install dvm (command-line,chocolatey,homebrew)?
homebrew

Do you like kittens? :smile_cat:  yes!

**Comment by carolynvs** [comment]
This is fixed on dvm [1.0](https://github.com/howtowhale/dvm/releases/tag/1.0.0). So after running `brew upgrade dvm`, it should work. Please let me know if you run into trouble!

**Comment by rayjohnson** [comment]
Ah!  Did not realize there was a new version!  I updated and all is well.

**Comment by carolynvs** [comment]
Huzzah! It's great to hear that it's working again! 💖
