### ISSUE TITLE
dvm deactivate does not do anything

### ISSUE THREAD

**Issue by rayjohnson** [howtowhale/dvm#186]
If you are reporting a bug, please use the template below:

### What didn't work?
I ran dvm deactivate hoping to get back to the system docker.  It did nothing.

```
$ env | grep PATH
PATH=/Users/rayj/.dvm/bin/docker/17.05.0-ce:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/rayj/go/bin:/usr/local/opt/go/libexec/bin10084
$ dvm deactivate
$ env | grep PATH
PATH=/Users/rayj/.dvm/bin/docker/17.05.0-ce:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/rayj/go/bin:/usr/local/opt/go/libexec/bin10084
```

### What should it have done?
I expect the first part of the PATH env to be removed.

### Helpful Context
If you can provide the following info, it will help us figure things out more quickly! :smile:

What version of dvm are you using?

```
$ dvm --version
Docker Version Manager version 0.9.0 ()
```

What is your Operating System?
Mac

What is your shell (bash/powershell/cmd/fish)?
bash

How did you install dvm (command-line,chocolatey,homebrew)?
homebrew

Do you like kittens? :smile_cat:  Yes!

**Comment by carolynvs** [comment]
Sorry for all the trouble! This is fixed by https://github.com/howtowhale/dvm/pull/182/commits/8d104c6475d5488b510ae40f9e3e527bfd96a78c and is included in dvm 1.0. So hopefully everything will be working again for you after upgrading. Let me know if there are any problems you run into.
