### ISSUE TITLE
Compatibility with future Go versions

### ISSUE THREAD

**Issue by Bo98** [howtowhale/dvm#195]
Just a heads up that Go 1.17 (and the just-released 1.16 without first changing `GO111MODULE`) won't support builds that aren't in module-aware mode.

I'm not sure what the status of this project is. Is there any plans to migrate to Go modules?

https://blog.golang.org/go116-module-changes

**Comment by carolynvs** [comment]
Thanks for the heads up! Yes, I'll move over to modules ASAP. 

The status of the project is "lightly maintained". I want it to keep working but don't have time to add new features.
